### ISSUE TITLE
Нарисован лишний Slot Connector

### ISSUE THREAD

**Issue by LeftyDeMilo** [amperka/hardware-drawings#104]
Для соединения Slot Expander к WiFi Slot достаточно использовать один Slot Connector. Ставить его лучше с лицевой стороны плат, чтобы не мешал размещению конструкции в WiFi Box (Структор). По этой же причине болты на Слот Коннекторе лучше развернуть на лицевую сторону плат.

Нарисован лишний Slot Connector (вернее слой Коннектора стоит разместить за слоями плат повернутых обратной стороной).

**Comment by igor605ds** [comment]
@LeftyDeMilo согласен с вами. В ближайшее время поправим. Спасибо за внимательность.
